# Generated by Django 4.2.27 on 2025-12-08 17:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Trial', max_length=20)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('transbank_api_key', models.TextField(blank=True, null=True)),
                ('transbank_commerce_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mercadopago_access_token', models.TextField(blank=True, null=True)),
                ('mercadopago_public_key', models.TextField(blank=True, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.TextField(blank=True, null=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('smtp_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=300, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subscription_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_products', models.IntegerField(default=100)),
                ('max_orders_per_month', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='idx_tenants_slug'), models.Index(fields=['status'], name='idx_tenants_status')],
            },
        ),
    ]
