# Generated by Django 4.2.27 on 2025-12-17 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('secret_key_encrypted', models.TextField(blank=True)),
                ('commerce_code_encrypted', models.TextField(blank=True)),
                ('public_key_encrypted', models.TextField(blank=True)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_gateway_configs',
                'ordering': ['gateway'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='payment_gat_tenant__86586f_idx'), models.Index(fields=['gateway'], name='payment_gat_gateway_a6adf1_idx')],
                'unique_together': {('tenant', 'gateway')},
            },
        ),
    ]
