# Generated by Django 4.2.27 on 2025-12-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Explorar Colección', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Cada pieza cuenta una historia de elegancia y funcionalidad', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_title',
            field=models.CharField(blank=True, default='El Arte del Diseño Minimalista', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shipping_mode',
            field=models.CharField(choices=[('Zones', 'Manual Zones'), ('Provider', 'External Provider'), ('Hybrid', 'Hybrid (Zones then Provider)')], default='Zones', max_length=20),
        ),
    ]
