# Generated by Django 4.2.27 on 2025-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_hero_cta_text_tenant_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='about_us_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='decimal_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='decimal_separator',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default='.', max_length=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='faq_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='our_history_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='prices_include_tax',
            field=models.BooleanField(default=False, help_text='If true, displayed prices include tax'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='privacy_policy_mode',
            field=models.CharField(choices=[('Default', 'Use Default'), ('Custom', 'Custom Text'), ('Url', 'External URL')], default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='privacy_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='refund_policy_mode',
            field=models.CharField(choices=[('Default', 'Use Default'), ('Custom', 'Custom Text'), ('Url', 'External URL')], default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='refund_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_product_ratings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_related_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Tax rate percentage (e.g. 19.00 for 19%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='thousands_separator',
            field=models.CharField(choices=[(',', ','), ('.', '.')], default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vision_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
