# Generated by Django 4.2.27 on 2025-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_about_us_text_tenant_allow_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='refund_policy_mode',
            new_name='terms_policy_mode',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='refund_policy_text',
            new_name='terms_policy_text',
        ),
        migrations.AddField(
            model_name='tenant',
            name='return_shipping_cost_cover',
            field=models.CharField(choices=[('Customer', 'Cliente'), ('Company', 'Empresa')], default='Customer', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='return_window_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shipping_days_max',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shipping_days_min',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='warranty_period',
            field=models.CharField(default='6 meses', max_length=50),
        ),
    ]
