# Generated by Django 4.2.27 on 2025-12-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_refund_policy_mode_tenant_terms_policy_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Ver Catálogo Completo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_description',
            field=models.TextField(blank=True, default='Descubre más de 100 productos diseñados para profesionales. Calidad premium y durabilidad garantizada.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_link',
            field=models.CharField(blank=True, default='/products', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_title',
            field=models.CharField(blank=True, default='Explora Toda Nuestra Colección', max_length=200, null=True),
        ),
    ]
