# Generated by Django 4.2.27 on 2025-12-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0006_tenant_cta_button_text_tenant_cta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_users',
                'indexes': [models.Index(fields=['user', 'tenant'], name='tenant_user_user_id_6c8fb2_idx')],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
