# Generated by Django 4.2.27 on 2026-01-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Propietario'), ('Admin', 'Administrador'), ('Operator', 'Operador')], default='Staff', max_length=20),
        ),
    ]
