# Generated by Django 4.2.27 on 2026-01-12 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenantuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='shipping_workdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Days of the week for shipping (0=Mon, 6=Sun)', size=None),
        ),
    ]
