# Generated by Django 4.2.27 on 2026-01-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_shipping_workdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='khipu_receiver_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='khipu_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago'), ('Khipu', 'Khipu')], max_length=20),
        ),
    ]
