# Generated by Django 4.2.27 on 2026-01-13 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenantmarketingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_path', models.CharField(help_text='The path to redirect from (e.g., /old-product-url)', max_length=500)),
                ('new_path', models.CharField(help_text='The path to redirect to (e.g., /products/new-product-url)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_redirects',
                'indexes': [models.Index(fields=['tenant', 'old_path'], name='idx_redirect_lookup')],
                'unique_together': {('tenant', 'old_path')},
            },
        ),
    ]
