# Generated by Django 4.2.27 on 2026-01-15 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='danger_color',
            field=models.CharField(default='#EF4444', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='info_color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='muted_color',
            field=models.CharField(default='#94A3B8', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='success_color',
            field=models.CharField(default='#10B981', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='warning_color',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
