# Generated by Django 4.2.27 on 2026-01-15 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_danger_color_tenant_info_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accent_dark_color',
            field=models.CharField(blank=True, help_text='Dark accent color for footer, Hero button (e.g., #2B2C30)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accent_medium_color',
            field=models.CharField(blank=True, help_text='Medium accent for CTA buttons (e.g., #3F4A52)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_text_color',
            field=models.CharField(blank=True, help_text='Text color for headers/footers on dark backgrounds (e.g., #F0EFEC)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
