# Generated by Django 4.2.27 on 2026-01-15 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_add_premium_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_text_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_dark_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_medium_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paleta Premium',
                'verbose_name_plural': 'Paletas Premium',
            },
        ),
    ]
