# Generated by Django 4.2.27 on 2026-01-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_create_premium_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Manual override for premium features'),
        ),
    ]
