# Generated by Django 4.2.27 on 2026-01-15 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_seed_premium_palettes'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpalette',
            name='cta_btn_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='cta_btn_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='cta_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='footer_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='footer_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='header_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='header_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='hero_btn_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='hero_btn_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='premiumpalette',
            name='hero_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_btn_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_btn_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cta_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='footer_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='footer_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='header_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='header_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_btn_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_btn_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hero_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
