# Generated by Django 4.2.27 on 2026-01-15 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_premiumpalette_cta_btn_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpalette',
            name='primary_btn_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_btn_text_color',
            field=models.CharField(blank=True, help_text='Text color for buttons using primary background (e.g., #FFFFFF)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid hex color', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
