# Generated by Django 4.2.27 on 2026-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_premiumpalette_primary_btn_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpalette',
            name='palette_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='premium', help_text='Type of palette: basic (available to all) or premium (requires premium plan)', max_length=10),
        ),
    ]
