# Generated by Django 4.2.27 on 2025-12-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
