# Generated by Django 4.2.27 on 2025-12-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_payment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='commune_codes',
            field=models.JSONField(default=list),
        ),
    ]
