# Generated by Django 4.2.27 on 2025-12-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_payments_tenant__5c7d9e_idx_payments_tenant__1040c7_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_tenant__1040c7_idx',
            old_name='payments_tenant__5c7d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_order_i_b32b33_idx',
            old_name='payments_order_i_3f8a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_gateway_f512b1_idx',
            old_name='payments_gateway_9b6c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_d621e5_idx',
            old_name='payments_status_2a8f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhooklog',
            new_name='payment_web_tenant__92389b_idx',
            old_name='payment_web_tenant__9a7c3e_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhooklog',
            new_name='payment_web_payment_37300d_idx',
            old_name='payment_web_payment_4f8b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentwebhooklog',
            new_name='payment_web_process_385493_idx',
            old_name='payment_web_process_7e9a1c_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='business_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list_type',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('VIP', 'VIP')], default='Retail', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='customers_tenant__074712_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'tax_id'], name='customers_tenant__96599e_idx'),
        ),
    ]
