# Generated by Django 4.2.27 on 2025-12-19 23:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_paymentgatewayconfig'),
        ('orders', '0007_rename_payments_tenant__5c7d9e_idx_payments_tenant__1040c7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.IntegerField(blank=True, default=1, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('applicable_to_categories', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('applicable_to_products', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.discountcoupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='discountcoupon',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=['tenant', 'code'], name='idx_coupons_active'),
        ),
        migrations.AddIndex(
            model_name='discountcoupon',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['tenant'], name='idx_discount_coupons_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='discountcoupon',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='unique_coupon_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='discountcoupon',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__gt', models.F('valid_from'))), name='check_coupon_dates'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon'], name='idx_coupon_usage_coupon_id'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['customer'], name='idx_coupon_usage_customer_id'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['tenant'], name='idx_coupon_usage_tenant_id'),
        ),
    ]
