# Generated by Django 4.2.27 on 2025-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_discountcoupon_couponusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('FixedAmount', 'Fixed Amount'), ('FreeShipping', 'Free Shipping')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='couponusage',
            table='coupon_usage',
        ),
        migrations.AlterModelTable(
            name='discountcoupon',
            table='discount_coupons',
        ),
    ]
