# Generated by Django 4.2.27 on 2025-12-21 19:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_refund_policy_mode_tenant_terms_policy_mode_and_more'),
        ('orders', '0009_alter_discountcoupon_discount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrierConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(choices=[('Starken', 'Starken'), ('Chilexpress', 'Chilexpress'), ('BlueExpress', 'Blue Express')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shipping_carrier_configs',
                'unique_together': {('tenant', 'carrier_name')},
            },
        ),
    ]
