# Generated by Django 4.2.27 on 2026-01-06 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shippingcarrierconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='commune_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
