# Generated by Django 4.2.27 on 2026-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_business_giro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_business_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_type',
            field=models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Boleta', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago'), ('Khipu', 'Khipu')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago'), ('Khipu', 'Khipu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='gateway',
            field=models.CharField(choices=[('Flow', 'Flow'), ('Transbank', 'Transbank WebPay Plus'), ('MercadoPago', 'Mercado Pago'), ('Khipu', 'Khipu')], max_length=20),
        ),
    ]
