# Generated by Django 4.2.27 on 2026-01-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_order_tenant_stat_created',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='idx_order_tenant_email',
        ),
    ]
