# Generated by Django 4.2.27 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_idx_order_tenant_stat_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='commune_codes',
            field=models.JSONField(default=list),
        ),
    ]
