# Generated by Django 4.2.27 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_idx_order_tenant_stat_created_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "shipping_zones" ALTER COLUMN "commune_codes" TYPE jsonb USING to_jsonb("commune_codes")',
            reverse_sql='ALTER TABLE "shipping_zones" ALTER COLUMN "commune_codes" TYPE character varying[] USING (SELECT array_agg(e)::character varying[] FROM jsonb_array_elements_text("commune_codes") as e)'
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='commune_codes',
            field=models.JSONField(default=list),
        ),
    ]
