# Generated by Django 4.2.27 on 2026-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_shipping_days',
            field=models.IntegerField(default=0, help_text='Minimum days required before shipping this product'),
        ),
    ]
