# Generated by Django 4.2.27 on 2026-01-16 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_seed_basic_palettes'),
        ('products', '0006_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_features',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_tenant_status_created',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_tenant_cat_status',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_tenant_feat_status',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='idx_var_product_active',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['product', 'sort_order'], name='product_fea_product_8a4253_idx'),
        ),
    ]
