# Generated by Django 4.2.27 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_referential_image',
            field=models.BooleanField(default=False, help_text="If true, shows 'Images are referential' disclaimer"),
        ),
    ]
