# Generated by Django 4.2.27 on 2025-12-19 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='INE code', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region_code', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communes',
                'ordering': ['region_code', 'name'],
                'indexes': [models.Index(fields=['name'], name='communes_name_f6f08f_idx'), models.Index(fields=['region_code'], name='communes_region__74f913_idx')],
            },
        ),
    ]
